trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image and push to container registry
      inputs:
        containerRegistry: 'juiceContainers'
        repository: 'juiceRepo'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
  - job: Test
    displayName: Test Azure
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: AzSKSVTs@4
      displayName: Run AzSK SVTs
      inputs:
        ConnectedServiceNameARM: 'Azure subscription 1 (a94e209d-614b-4e3f-8a8f-56b3b44a2d62)'
        GenerateMethodParameterSetSelection: 'ResourceGroupName'
        ResourceGroupName: 'juiceShopTesting'
        SubscriptionId: 'a94e209d-614b-4e3f-8a8f-56b3b44a2d62'
        EnableOMSLogging: false